#!/bin/bash
# Idea for the script came from https://github.com/t3rmin4t0r/notes/wiki/LXC-DNS-setup

#Fix the /etc/init/lxc-net.conf file
/bin/sed -i "s/dnsmasq -u lxc-dnsmasq --strict-order/dnsmasq -u lxc-dnsmasq --server=\/lxc\/ --domain lxc --strict-order/g" /etc/init/lxc-net.conf

# Add .lxc domains to NetworkManager
if [ ! -f /etc/NetworkManager/dnsmasq.d/lxc.conf ]; then
    echo -e "local=/lxc/10.0.3.1" > /etc/NetworkManager/dnsmasq.d/lxc.conf
fi

exit 0
